import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import Light from '../public/light.svg'

import EnDescription from "./locales/en/description.json";
import FrDescription from "./locales/fr/description.json";





// const trad = {
//   en: {
//     translation: {
//       "Description": "Description en"
//     }
//   },
//   fr: {
//     translation: {
//       "Description": "Description fr"
//     }
//   }
// }

const Home = (props: any) => {

    const locale = props.lng;
  
    let description = '';
    if(locale === 'fr') {
      description = FrDescription.Description;
    } else {
       description = EnDescription.Description;
    }

 
  return (
    <>
      <Head>
        <title>Mon Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400&display=swap"
          rel="stylesheet"
        />
      </Head>
      
      <main className={styles.container}>
          <div className={styles.orbe1}></div>
          <div className={styles.orbe2}></div>
          <div className={styles.orbe3}></div>
          <div>
            <div className='center-element'>
              <Light className={`ampoule`}/>
            </div>
          </div> 

          <div className={`description_grid`}>
            <p className='description'>
              {description}
            </p>
            <p>photo</p>
          </div>
      </main>
    </>
  )
}

export default Home;
